spring:
  profiles:
    active: dev  # 当前选择使用下面的dev配置
        
---
spring:
  profiles: dev
  application:
    name: springcloud-config-dev
     
---
spring:
  profiles: test
  application:
    name: springcloud-config-test
