spring:
    profiles:
        active: test
        
---
server:
  port: 8001

mybatis:
  type-aliases-package: com.pkh.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

spring:
  profiles: dev
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEnciding=true&serverTimezone=GMT
    username: root
    password: a1274969770

# Eureka的配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ # 发布到注册中心集群中
  instance:
    prefer-ip-address: true # 使用ip地址注册
    instance-id: springcloud-provider-dept8001 # 修改eureka上默认的status描述信息！

# info配置
info:
  app.name: pkh-springcloud
  company.name: zhijiang.pkh.com

---
server:
  port: 8001

mybatis:
  type-aliases-package: com.pkh.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

spring:
  profiles: test
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEnciding=true&serverTimezone=GMT
    username: root
    password: a1274969770

# Eureka的配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ # 发布到注册中心集群中
  instance:
    prefer-ip-address: true # 使用ip地址注册
    instance-id: springcloud-provider-dept8001 # 修改eureka上默认的status描述信息！

# info配置
info:
  app.name: pkh-springcloud
  company.name: zhijiang.pkh.com

