spring:
    profiles:
        active: dev
---
server:
  port: 7001

spring:
    profiles: dev
    application:
        name: springcloud-config-eureka
        
# Eureka配置
eureka:
  instance:
    hostname: eureka7001.com #Eureka服务端的实例名称
  client:
    register-with-eureka: false # 表示是否向eureka注册中心注册自己
    fetch-registry: false # fetch-registry如果为false，则表示自己为注册中心
    server-url: #监控页面
      # 单机：defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群（多个注册中心相互关联） 要想实现还要再C:\Windows\System32\drivers\etc的host文件中加上  127.0.0.1  eureka7001.com   和  127.0.0.1  eureka7002.com和  127.0.0.1  eureka7003.com
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

---
server:
  port: 7001

spring:
    profiles: test
    application:
        name: springcloud-config-eureka
        
# Eureka配置
eureka:
  instance:
    hostname: eureka7001.com #Eureka服务端的实例名称
  client:
    register-with-eureka: false # 表示是否向eureka注册中心注册自己
    fetch-registry: false # fetch-registry如果为false，则表示自己为注册中心
    server-url: #监控页面
      # 单机：defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群（多个注册中心相互关联） 要想实现还要再C:\Windows\System32\drivers\etc的host文件中加上  127.0.0.1  eureka7001.com   和  127.0.0.1  eureka7002.com和  127.0.0.1  eureka7003.com
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
